In [1]:
from datetime import datetime
import time
import pandas as pd
import numpy as np

In [2]:
# for other subjects, change the 'S6' in the file path to appropriate subject folder and run the same script

In [3]:
df = pd.read_csv('Data\\Raw Data\\S6\\Pectoralis – chest\\accel.csv')
df

      Timestamp (microseconds)  Accel X (g)  Accel Y (g)  Accel Z (g)
0                 1.604169e+15    -0.018494     0.764721     0.702220
1                 1.604169e+15    -0.001404     0.742748     0.640208
2                 1.604169e+15     0.008850     0.735424     0.628000
3                 1.604169e+15     0.009827     0.767651     0.669017
4                 1.604169e+15     0.033753     0.755444     0.698802
...                        ...          ...          ...          ...
8931              1.604171e+15     0.275944     0.718822     0.477607
8932              1.604171e+15     0.298405     0.607492     0.387274
8933              1.604171e+15     0.193423     0.737377     0.663645
8934              1.604171e+15    -0.126894     0.984939     0.949294
8935              1.604171e+15    -0.190860     0.833570     0.908278

[8936 rows x 4 columns]

In [4]:
df2 = pd.read_csv('Data\\Raw Data\\S6\\Pectoralis – chest\\elec.csv')
df2

       Timestamp (microseconds)  Sample (V)
0                  1.604169e+15   -0.010490
1                  1.604169e+15   -0.010490
2                  1.604169e+15   -0.010484
3                  1.604169e+15   -0.010496
4                  1.604169e+15   -0.010484
...                         ...         ...
71060              1.604171e+15   -0.010706
71061              1.604171e+15   -0.010669
71062              1.604171e+15   -0.010656
71063              1.604171e+15   -0.010663
71064              1.604171e+15   -0.010656

[71065 rows x 2 columns]

# Merging data

In [5]:
elec_ts = df2['Timestamp (microseconds)'].to_numpy()
elec_ts

array([1.60416931e+15, 1.60416931e+15, 1.60416931e+15, ...,
       1.60417092e+15, 1.60417092e+15, 1.60417092e+15])

In [6]:
accel_ts = df['Timestamp (microseconds)'].to_numpy()
accel_ts

array([1.60416931e+15, 1.60416931e+15, 1.60416931e+15, ...,
       1.60417092e+15, 1.60417092e+15, 1.60417092e+15])

In [7]:
for i in range(len(accel_ts)):
    df.at[i, 'Sample (V)'] = df2['Sample (V)'].iloc[np.argmin(abs(accel_ts[i] - elec_ts))]

In [8]:
df

,Timestamp (microseconds),Accel X (g),Accel Y (g),Accel Z (g),Sample (V)
0,1.604169e+15,-0.018494,0.764721,0.702220,-0.010490
1,1.604169e+15,-0.001404,0.742748,0.640208,-0.010460
2,1.604169e+15,0.008850,0.735424,0.628000,-0.010496
3,1.604169e+15,0.009827,0.767651,0.669017,-0.010466
4,1.604169e+15,0.033753,0.755444,0.698802,-0.010306
...,...,...,...,...,...
8931,1.604171e+15,0.275944,0.718822,0.477607,-0.010890
8932,1.604171e+15,0.298405,0.607492,0.387274,-0.010933
8933,1.604171e+15,0.193423,0.737377,0.663645,-0.010890
8934,1.604171e+15,-0.126894,0.984939,0.949294,-0.010878
8935,1.604171e+15,-0.190860,0.833570,0.908278,-0.010736

# Data filtering and adding labels

In [9]:
print(df['Timestamp (microseconds)'][0])
pd.Timestamp(df['Timestamp (microseconds)'][0], unit='us')

1604169310003850.0

Timestamp('2020-10-31 18:35:10.003850')

In [10]:
# These values are obtained from the Meta Data and converted to UTC from Est 

start = pd.Timestamp(year = 2020, month = 10, day = 31, hour = 18, minute = 35, second = 10)
start_ts = int(start.timestamp() * 1e6)

end = pd.Timestamp(year = 2020, month = 10, day = 31, hour = 18, minute = 36, second = 39)
end_ts = int(end.timestamp() * 1e6)

stairs = df.loc[(df['Timestamp (microseconds)'] >= start_ts) & (df['Timestamp (microseconds)'] <= end_ts)]

stairs['Activity_Label'] = 'stairs'
stairs

C:\Users\mahaj\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

,Timestamp (microseconds),Accel X (g),Accel Y (g),Accel Z (g),Sample (V),Activity_Label
0,1.604169e+15,-0.018494,0.764721,0.702220,-0.010490,stairs
1,1.604169e+15,-0.001404,0.742748,0.640208,-0.010460,stairs
2,1.604169e+15,0.008850,0.735424,0.628000,-0.010496,stairs
3,1.604169e+15,0.009827,0.767651,0.669017,-0.010466,stairs
4,1.604169e+15,0.033753,0.755444,0.698802,-0.010306,stairs
...,...,...,...,...,...,...
2795,1.604169e+15,0.057191,0.815015,0.888258,-0.010324,stairs
2796,1.604169e+15,0.104555,0.809155,0.838941,-0.010300,stairs
2797,1.604169e+15,0.085512,0.728588,0.629465,-0.010318,stairs
2798,1.604169e+15,0.063539,0.615793,0.629465,-0.010226,stairs
2799,1.604169e+15,0.003479,0.613352,0.648997,-0.010207,stairs

In [11]:
start = pd.Timestamp(year = 2020, month = 10, day = 31, hour = 18, minute = 44, second = 30)
start_ts = int(start.timestamp() * 1e6)

end = pd.Timestamp(year = 2020, month = 10, day = 31, hour = 18, minute = 45, second = 56)
end_ts = int(end.timestamp() * 1e6)

jog = df.loc[(df['Timestamp (microseconds)'] >= start_ts) & (df['Timestamp (microseconds)'] <= end_ts)]

jog['Activity_Label'] = 'jog'
jog

C:\Users\mahaj\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

,Timestamp (microseconds),Accel X (g),Accel Y (g),Accel Z (g),Sample (V),Activity_Label
2800,1.604170e+15,0.083070,0.692454,0.698802,-0.010509,jog
2801,1.604170e+15,0.097230,0.689036,0.701732,-0.010484,jog
2802,1.604170e+15,0.109926,0.701244,0.716869,-0.010472,jog
2803,1.604170e+15,0.105531,0.719799,0.717845,-0.010521,jog
2804,1.604170e+15,0.080140,0.741772,0.742748,-0.010533,jog
...,...,...,...,...,...,...
5501,1.604170e+15,-0.105898,0.310613,0.261295,-0.010460,jog
5502,1.604170e+15,0.005432,0.596750,0.478584,-0.010447,jog
5503,1.604170e+15,0.089906,1.021073,0.822827,-0.010386,jog
5504,1.604170e+15,0.000061,1.202228,1.195880,-0.010355,jog
5505,1.604170e+15,0.083070,1.206134,1.192462,-0.010429,jog

In [12]:
start = pd.Timestamp(year = 2020, month = 10, day = 31, hour = 18, minute = 50, second = 45)
start_ts = int(start.timestamp() * 1e6)

end = pd.Timestamp(year = 2020, month = 10, day = 31, hour = 18, minute = 50, second = 55)
end_ts = int(end.timestamp() * 1e6)

skip = df.loc[(df['Timestamp (microseconds)'] >= start_ts) & (df['Timestamp (microseconds)'] <= end_ts)]
skip['Activity_Label'] = 'skipping'
skip

C:\Users\mahaj\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Timestamp (microseconds),Accel X (g),Accel Y (g),Accel Z (g),Sample (V),Activity_Label
5506,1.604170e+15,0.276921,0.728099,0.542061,-0.011844,skipping
5507,1.604170e+15,0.275456,0.759350,0.593820,-0.011617,skipping
5508,1.604170e+15,0.254459,0.819409,0.503487,-0.011315,skipping
5509,1.604170e+15,0.069398,0.788159,0.695872,-0.011106,skipping
5510,1.604170e+15,0.128969,0.414130,0.485908,-0.010940,skipping
...,...,...,...,...,...,...
5815,1.604170e+15,0.028382,-0.919387,-0.146914,-0.012023,skipping
5816,1.604170e+15,-0.069276,-0.515572,0.227604,-0.012503,skipping
5817,1.604170e+15,0.146059,0.328191,0.715892,-0.013684,skipping
5818,1.604170e+15,-0.295354,-0.026307,1.021073,-0.012497,skipping
5819,1.604170e+15,-0.007263,-0.205509,0.529854,-0.011795,skipping

In [13]:
start = pd.Timestamp(year = 2020, month = 10, day = 31, hour = 18, minute = 57, second = 30)
start_ts = int(start.timestamp() * 1e6)

end = pd.Timestamp(year = 2020, month = 10, day = 31, hour = 18, minute = 58, second = 11)
end_ts = int(end.timestamp() * 1e6)

kb = df.loc[(df['Timestamp (microseconds)'] >= start_ts) & (df['Timestamp (microseconds)'] <= end_ts)]
kb['Activity_Label'] = 'kettlebell'
kb

C:\Users\mahaj\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Timestamp (microseconds),Accel X (g),Accel Y (g),Accel Z (g),Sample (V),Activity_Label
5820,1.604171e+15,0.099672,0.728099,0.730541,-0.010546,kettlebell
5821,1.604171e+15,0.102113,0.692943,0.754955,-0.010306,kettlebell
5822,1.604171e+15,0.092348,0.691966,0.706615,-0.010601,kettlebell
5823,1.604171e+15,0.092836,0.669505,0.745190,-0.010607,kettlebell
5824,1.604171e+15,0.097719,0.669993,0.773510,-0.010595,kettlebell
...,...,...,...,...,...,...
7103,1.604171e+15,-0.014588,0.676829,0.551339,-0.010509,kettlebell
7104,1.604171e+15,-0.012634,0.669017,0.507393,-0.010496,kettlebell
7105,1.604171e+15,-0.054139,0.627024,0.473701,-0.010484,kettlebell
7106,1.604171e+15,-0.032654,0.589425,0.335515,-0.010466,kettlebell
7107,1.604171e+15,-0.027771,0.687083,0.218814,-0.010386,kettlebell

In [14]:
start = pd.Timestamp(year = 2020, month = 10, day = 31, hour = 19, minute = 1, second = 0)
start_ts = int(start.timestamp() * 1e6)

end = pd.Timestamp(year = 2020, month = 10, day = 31, hour = 19, minute = 2, second = 11)
end_ts = int(end.timestamp() * 1e6)

bb = df.loc[(df['Timestamp (microseconds)'] >= start_ts) & (df['Timestamp (microseconds)'] <= end_ts)]
bb['Activity_Label'] = 'basket ball'
bb

C:\Users\mahaj\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Timestamp (microseconds),Accel X (g),Accel Y (g),Accel Z (g),Sample (V),Activity_Label
7108,1.604171e+15,-0.011658,0.624582,0.805737,-0.010515,basket ball
7109,1.604171e+15,-0.010681,0.614817,0.815991,-0.010515,basket ball
7110,1.604171e+15,-0.011658,0.606027,0.817945,-0.010453,basket ball
7111,1.604171e+15,-0.007752,0.633371,0.779370,-0.010558,basket ball
7112,1.604171e+15,0.002502,0.589914,0.828199,-0.010527,basket ball
...,...,...,...,...,...,...
8931,1.604171e+15,0.275944,0.718822,0.477607,-0.010890,basket ball
8932,1.604171e+15,0.298405,0.607492,0.387274,-0.010933,basket ball
8933,1.604171e+15,0.193423,0.737377,0.663645,-0.010890,basket ball
8934,1.604171e+15,-0.126894,0.984939,0.949294,-0.010878,basket ball
8935,1.604171e+15,-0.190860,0.833570,0.908278,-0.010736,basket ball

In [15]:
merged_df = pd.concat([stairs, jog, skip, kb, bb], ignore_index=True)

In [16]:
merged_df

,Timestamp (microseconds),Accel X (g),Accel Y (g),Accel Z (g),Sample (V),Activity_Label
0,1.604169e+15,-0.018494,0.764721,0.702220,-0.010490,stairs
1,1.604169e+15,-0.001404,0.742748,0.640208,-0.010460,stairs
2,1.604169e+15,0.008850,0.735424,0.628000,-0.010496,stairs
3,1.604169e+15,0.009827,0.767651,0.669017,-0.010466,stairs
4,1.604169e+15,0.033753,0.755444,0.698802,-0.010306,stairs
...,...,...,...,...,...,...
8931,1.604171e+15,0.275944,0.718822,0.477607,-0.010890,basket ball
8932,1.604171e+15,0.298405,0.607492,0.387274,-0.010933,basket ball
8933,1.604171e+15,0.193423,0.737377,0.663645,-0.010890,basket ball
8934,1.604171e+15,-0.126894,0.984939,0.949294,-0.010878,basket ball
8935,1.604171e+15,-0.190860,0.833570,0.908278,-0.010736,basket ball

In [17]:
merged_df.to_csv('Data\\Intermediate Data\\S6\\Pectoralis – chest\\accel+elec.csv', index = False)